# pamu2fcfg -ubotany_adm -opam://botany.pl -ipam://botany.pl | tee u2f_keys
# pamu2fcfg -n -ubotany_adm -opam://botany.pl -ipam://botany.pl | tee -a u2f_keys

origin = pam://botany.pl
appid = pam://botany.pl
authfile = /usr/share/botany/u2f_keys
