#!/bin/bash
## setup auto-unlock LUKS2 encrypted root on Fedora/Silverblue/maybe others
set -eou pipefail

[ "$UID" -eq 0 ] || { echo "This script must be run as root."; exit 1;}

echo "WARNING: Do NOT use this if your CPU is vulnerable to faulTPM!"
echo "All AMD Zen2 and Zen3 Processors are known to be affected!"
echo "All AMD Zen1 processors are also likely affected, with Zen4 unknown!"
echo "If you have an AMD CPU, you likely shouldn't use this!"
echo "----------------------------------------------------------------------------"
echo "This script uses systemd-cryptenroll to enable TPM2 auto-unlock."
echo "You can review systemd-cryptenroll's manpage for more information."
echo "This script will modify your system."
echo "It will enable TPM2 auto-unlock of your LUKS partition for your root device!"
echo "It will bind to PCR 7 and 14 which is tied to your secureboot and moklist state."
read -p "Are you sure are good with this and want to enable TPM2 auto-unlock? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi

## Inspect Kernel Cmdline for rd.luks.uuid
RD_LUKS_UUID="$(xargs -n1 -a /proc/cmdline | grep rd.luks.uuid | cut -d = -f 2)"

# Check to make sure cmdline rd.luks.uuid exists
if [[ -z ${RD_LUKS_UUID:-} ]]; then
  printf "LUKS device not defined on Kernel Commandline.\n"
  printf "This is not supported by this script.\n"
  printf "Exiting...\n"
  exit 1
fi

# Check to make sure that the specified cmdline uuid exists.
if ! grep -q "${RD_LUKS_UUID}" <<< "$(lsblk)" ; then
  printf "LUKS device not listed in block devices.\n"
  printf "Exiting...\n"
  exit 1
fi

# Cut off the luks-
LUKS_PREFIX="luks-"
if grep -q ^${LUKS_PREFIX} <<< "${RD_LUKS_UUID}"; then
  DISK_UUID=${RD_LUKS_UUID#"$LUKS_PREFIX"}
else
  echo "LUKS UUID format mismatch."
  echo "Exiting..."
  exit 1
fi

# Specify Crypt Disk by-uuid
CRYPT_DISK="/dev/disk/by-uuid/$DISK_UUID"

# Check to make sure crypt disk exists
if [[ ! -L "$CRYPT_DISK" ]]; then
  printf "LUKS device not listed in block devices.\n"
  printf "Exiting...\n"
  exit 1
fi

if ! grep -q tpm2-tss <<< "$(lsinitrd)"; then
  # This shouldn't ever be the case nowadays, so I keep this as a sanity check.
  echo "ERROR: tpm2-tss is not in initramfs"
  #if rpm-ostree initramfs | grep tpm2 > /dev/null; then
  #  echo "TPM2 already present in rpm-ostree initramfs config, so should will be put into initramfs the next time it is re-generated."
  #else
  #  echo "Enabling rpm-ostree initramfs generation and force-adding tpm2-tss to its module list."
  #  rpm-ostree initramfs --enable --arg=--force-add --arg=tpm2-tss
  #fi
  exit 1
#else
  #echo "tpm2-tss already present in current initramfs. Good."
  #read -rs -p "Press enter to continue..."
fi

if cryptsetup luksDump "$CRYPT_DISK" | grep -q systemd-tpm2; then
  KEYSLOT=$(cryptsetup luksDump "$CRYPT_DISK" | sed -n '/systemd-tpm2$/,/Keyslot:/p' | grep Keyslot|awk '{print $2}')
  echo "TPM2 already present in LUKS keyslot $KEYSLOT of $CRYPT_DISK."
  read -p "Wipe it and re-enroll? (y/N): " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Wiping TPM2 slot now..."
    echo systemd-cryptenroll --wipe-slot=tpm2 "$CRYPT_DISK"
    systemd-cryptenroll --wipe-slot=tpm2 "$CRYPT_DISK"
  else
    echo
    echo "Either clear the existing TPM2 keyslot before retrying, else choose 'y' next time."
    echo "Exiting..."
    [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1
  fi
fi

SET_RECOVERY_KEY_ARG="--recovery-key"
if grep -q "recovery" <<< "$(systemd-cryptenroll "$CRYPT_DISK")"; then
  echo "Recovery key already present in LUKS cryptdisk $CRYPT_DISK."
  read -p "Wipe it and re-enroll? (y/N): " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    SET_RECOVERY_KEY_ARG="--recovery-key --wipe-slot=recovery"
  else
    echo "Keeping the existing recovery key intact... Make sure you have it backed up!"
    SET_RECOVERY_KEY_ARG=""
  fi
fi

WIPE_PASSWORD_ARG=""
if grep -q "password" <<< "$(systemd-cryptenroll "$CRYPT_DISK")"; then
  WIPE_PASSWORD_ARG="--wipe-slot=password"
  read -p "Wipe the password slot? (Y/n): " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Nn]$ ]]; then
    WIPE_PASSWORD_ARG=""
  fi
fi

SET_TPM_PIN_ARG=""
read -p "Would you like to set a PIN? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  SET_TPM_PIN_ARG="--tpm2-with-pin=yes"
fi

## Run crypt enroll
echo "Enrolling TPM2 unlock requires your existing LUKS2 unlock password"
echo "Enrolling TPM2 now..."
echo systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7+14 $SET_TPM_PIN_ARG "$CRYPT_DISK"
systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7+14 $SET_TPM_PIN_ARG "$CRYPT_DISK"

echo

if [[ -z "$SET_RECOVERY_KEY_ARG" && -z "$WIPE_PASSWORD_ARG" ]]; then
  echo "WARN: Not setting a new recovery key and not wiping a password!"
else
  RECOV_DMP="/tmp/luks_crypt_recovery_key_${HOSTNAME}.txt"
  hostnamectl > "$RECOV_DMP"
  ip -brief link | grep -vE '^lo\s+' >> "$RECOV_DMP"
  dmidecode --type 0,1,2 --quiet >> "$RECOV_DMP"
  lsblk >> "$RECOV_DMP"

  if [[ -z "$SET_RECOVERY_KEY_ARG" ]]; then echo "Wiping password now... (will also save it to ${RECOV_DMP})"
  elif [[ -z "$WIPE_PASSWORD_ARG" ]]; then echo "Enrolling recovery key now... (will also save it to ${RECOV_DMP})"
  else echo "Enrolling recovery key and wiping password now... (will also save it to ${RECOV_DMP})"
  fi

  echo systemd-cryptenroll $SET_RECOVERY_KEY_ARG $WIPE_PASSWORD_ARG "$CRYPT_DISK"
  systemd-cryptenroll $SET_RECOVERY_KEY_ARG $WIPE_PASSWORD_ARG "$CRYPT_DISK" 2>&1 | tee -a "$RECOV_DMP"
  echo "Currently enrolled slots:" >> "$RECOV_DMP"
  systemd-cryptenroll "$CRYPT_DISK" >> "$RECOV_DMP"
fi


## Now reboot
echo "Currently enrolled slots:"
systemd-cryptenroll "$CRYPT_DISK"
echo
echo "TPM2 LUKS auto-unlock configured. Reboot now."

# References:
#  https://www.reddit.com/r/Fedora/comments/uo4ufq/any_way_to_get_systemdcryptenroll_working_on/
#  https://0pointer.net/blog/unlocking-luks2-volumes-with-tpm2-fido2-pkcs11-security-hardware-on-systemd-248.html
#  https://github.com/ublue-os/packages/blob/main/packages/ublue-os-luks/src/luks-enable-tpm2-autounlock
#  https://www.reddit.com/r/Fedora/comments/uo4ufq/comment/ivg34sr/
