name: Promote latest to prod
on:
  workflow_dispatch:

env:
  IMAGE_NAME: "${{ github.event.repository.name }}"
  IMAGE_REGISTRY: "${{ secrets.IMAGE_REGISTRY }}"
  TAG_OLD: "latest"
  TAG_NEW: "prod"
  #CONTENT_TYPE: "application/vnd.docker.distribution.manifest.v2+json"
  CONTENT_TYPE: "application/vnd.oci.image.manifest.v1+json"
  U: "${{ secrets.REGISTRY_USER }}:${{ secrets.REGISTRY_PASSWORD }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: false

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate
        id: auth
        run: |
          echo "::add-mask::$(base64 <<< "${U}")"
          REGISTRY_TOKEN=$(curl -v -u "${U}" --no-progress-meter "https://${IMAGE_REGISTRY}/auth?scope=repository:${IMAGE_NAME}:pull,push&service=Docker%20registry" | jq -r '.token')
          echo "::add-mask::${REGISTRY_TOKEN}"
          echo "token=${REGISTRY_TOKEN}" >> "$GITHUB_OUTPUT"

      - name: Get manifest (from old tag)
        run: |
          REGISTRY_TOKEN=${{ steps.auth.outputs.token }}"
          curl -o /tmp/manifest.json -v -H "Accept: ${CONTENT_TYPE}" -H "Authorization: Bearer ${REGISTRY_TOKEN}" --no-progress-meter "https://${IMAGE_REGISTRY}/v2/${IMAGE_NAME}/manifests/${TAG_OLD}"

      - name: Print manifest
        run: |
          jq --color-output < /tmp/manifest.json

      - name: Submit manifest (to new tag)
        run: |
          REGISTRY_TOKEN=${{ steps.auth.outputs.token }}"
          curl -v -X PUT -H "Content-Type: ${CONTENT_TYPE}" --data-binary "@/tmp/manifest.json" -H "Authorization: Bearer ${REGISTRY_TOKEN}" --no-progress-meter "https://${IMAGE_REGISTRY}/v2/${IMAGE_NAME}/manifests/${TAG_NEW}"
